"""
Drag icon_500.png into the same folder as this script, then run it.
Only needs Pillow: pip install pillow
Outputs: icon.ico and src/icon_data.rs
"""

import os, io, struct
from PIL import Image

BASE     = os.path.dirname(os.path.abspath(__file__))
SRC      = os.path.join(BASE, "icon_500.png")
ICO_PATH = os.path.join(BASE, "icon.ico")
RS_PATH  = os.path.join(BASE, "src", "icon_data.rs")
os.makedirs(os.path.join(BASE, "src"), exist_ok=True)

SIZES = [16, 32, 48, 64, 128, 256]

def make_ico(images):
    num = len(images)
    header = struct.pack("<HHH", 0, 1, num)
    entries = b""
    data    = b""
    offset  = 6 + num * 16
    for img in images:
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        png = buf.getvalue()
        w, h = img.size
        iw = w if w < 256 else 0
        ih = h if h < 256 else 0
        entries += struct.pack("<BBBBHHII", iw, ih, 0, 0, 1, 32, len(png), offset)
        data   += png
        offset += len(png)
    return header + entries + data

def fmt_rs(data):
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ",".join(str(b) for b in data[i:i+16]) + ",")
    return "\n".join(rows)

def img_const(img, name):
    w, h = img.size
    return (
        f"pub const {name}_RGBA: &[u8] = &[\n{fmt_rs(img.tobytes())}\n];\n"
        f"pub const {name}_W: u32 = {w};\n"
        f"pub const {name}_H: u32 = {h};\n"
    )

print(f"Loading {SRC}...")
src_img = Image.open(SRC).convert("RGBA")

print("Resizing to all sizes...")
images = {}
for size in SIZES:
    images[size] = src_img.resize((size, size), Image.LANCZOS)
    print(f"  {size}x{size}")

print(f"\nWriting {ICO_PATH}...")
with open(ICO_PATH, "wb") as f:
    f.write(make_ico([images[s] for s in SIZES]))
print(f"  OK ({os.path.getsize(ICO_PATH):,} bytes)")

print(f"Writing {RS_PATH}...")
rs  = "// Auto-generated by make_icon.py — do not edit\n#![allow(dead_code)]\n\n"
rs += img_const(images[16], "ICON_16")
rs += "\n"
rs += img_const(images[32], "ICON_32")
with open(RS_PATH, "w", encoding="utf-8") as f:
    f.write(rs)
print(f"  OK")

print("\nDone. Now run: cargo build --release")
